-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 00:36:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET
@OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample-jpa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sample-jpa`;

-- -----------------------------------------------------
-- Schema sample-jpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample-jpa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE
`sample-jpa` ;

-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status`
(
  `id`
  INT
  UNSIGNED
  NOT
  NULL,
  `name`
  VARCHAR
(
  45
) NOT NULL,
  PRIMARY KEY
(
  `id`
),
  UNIQUE INDEX `uq_status_name`
(
  `name` ASC
))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`
(
  `id`
  BIGINT
  UNSIGNED
  NOT
  NULL
  AUTO_INCREMENT,
  `name`
  VARCHAR
(
  45
) NOT NULL,
  `bio` TEXT NOT NULL,
  PRIMARY KEY
(
  `id`
),
  UNIQUE INDEX `uq_user_name`
(
  `name` ASC
))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`
(
  `id`
  BIGINT
  UNSIGNED
  NOT
  NULL
  AUTO_INCREMENT,
  `user`
  BIGINT
  UNSIGNED
  NOT
  NULL,
  `title`
  VARCHAR
(
  255
) NOT NULL,
  `detail` TEXT NOT NULL,
  `status` INT UNSIGNED NOT NULL,
  `parent` BIGINT UNSIGNED NULL,
  PRIMARY KEY
(
  `id`
),
  INDEX `fk_todo_pk_status`
(
  `status` ASC
),
  INDEX `fk_todo_pk_user`
(
  `user` ASC
),
  INDEX `fk_todo_parent_pk_todo`
(
  `parent` ASC
),
  CONSTRAINT `fk_todo_pk_status`
  FOREIGN KEY
(
  `status`
)
  REFERENCES `status`
(
  `id`
)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_pk_user`
  FOREIGN KEY
(
  `user`
)
  REFERENCES `user`
(
  `id`
)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_parent_pk_todo`
  FOREIGN KEY
(
  `parent`
)
  REFERENCES `todo`
(
  `id`
)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET
SQL_MODE=@OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `status`
-- -----------------------------------------------------
START TRANSACTION;
USE
`sample-jpa`;
INSERT INTO `status` (`id`, `name`)
VALUES (0, 'TODO');
INSERT INTO `status` (`id`, `name`)
VALUES (1, 'WORKING');
INSERT INTO `status` (`id`, `name`)
VALUES (2, 'DONE');
INSERT INTO `status` (`id`, `name`)
VALUES (3, 'CANCEL');

COMMIT;

